#!/usr/bin/env bash
# Classic fizz buzz, Displays numbers from 1 to 100.

for ((i = 1; i <= 100; i++))
do
	if (("${i}" % 5 == 0 && "${i}" % 3 == 0))
	then
		echo "FizzBuzz"
	elif (("${i}" % 5 == 0))
	then
		echo "Buzz"
	elif (("${i}" % 3 == 0))
	then
		echo "Fizz"
	else
		echo "${i}"
	fi
done
