#!/usr/bin/env bash
# Display Best School and in certain iterations displays good luck or bad luck

i=0

while [ "${i}" -lt 10 ]
do
	if [ "${i}" -eq 3 ]
	then
		echo "bad luck"
	elif [ "${i}" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
