#!/usr/bin/env bash
# Displays numbers from 1 to 20 and in the 4th, 9th and 17th displays bad luck respectively (China, Japan and Italy)

i=1

while [ "${i}" -lt 21 ]
do
	echo "${i}"
	case "${i}" in
	4)
		echo "bad luck from China"
	;;
	9)
		echo "bad luck from Japan"
	;;
	17)
		echo "bad luck from Italy"
	;;
	esac
	((i++))
done
